### ISSUE TITLE
PostgreDatabase Mock for Unit Testing

### ISSUE THREAD

**Issue by mcmikius** [LLCFreedom-Space/fs-app-health-checks#19]
**Problem**

Currently, it is impossible to write unit tests for the PostgreDatabase functionality because it directly interacts with a running PostgreSQL server. This is inconvenient because it:

- Slows down development
- Requires a PostgreSQL server to be present
- Does not allow testing code in isolation

** Solution**
Make PostgreDatabase available as a Mock for writing unit tests. This will allow:

- Testing PostgreDatabase code in isolation
- Speeding up development
- Not depending on the presence of a PostgreSQL server

**Describe alternatives you've considered**
- Use a test PostgreSQL server. This is not very convenient because it requires its installation and configuration.
- Do not write tests for PostgreDatabase functionality. This is not recommended as it reduces the code quality.

**Additional context**
None

**Comment by gulivero1773** [comment]
There are two methods of solving the issue:

- Check for Environment in function - getVersion. If .testing then return - it is ok
- Create protocol for one function - getVersion and if test use mock function
